### PR TITLE
set BatchAddressSearch as landing page

### PR DESCRIPTION
**Pull request by wingkwong**
ref to #62

- Showing corresponding ResultCard as feature overlay when clicking a marker
- Isolated ResultTable. Caller has been commented out in BatchAddressSearcher.vue as showing the table within that width is not user-friendly
- Revised layout
- Removed AddressSearcher.vue
- Revised routing and header links
- Merged with Multi-source branch

### CODE REVIEW

**Comment by cswbrian** [comment]
- input '政府總部' but no result, console log showed error message, perhaps due to different source
- input '九龍油麻地眾坊街60號地下', but display multiple markers, perhaps normalizedresult consists of all possible matches instead of the top match

**Comment by wingkwong** [comment]
for the first point, I'll check later

for the second point, is displaying multiple markers on the map not expected? If normalizedresult consists only one result, then there will be only one marker there.

**Comment by cswbrian** [comment]
image

for the second point, when user inputs '九龍油麻地眾坊街60號地下', it shows all possible matches for this certain input, but it is supposed to show only one top match.

If user inputs 
九龍油麻地眾坊街60號地下
九龍油麻地海泓道10號,
there will be two markers only on the map (top match of each input) 

Btw would you mind move the commit into another branch and then make a PR?

**Comment by wingkwong** [comment]
I see. Thanks for clarification. I'll revise it and make the PR to multi-source branch instead.

**Pull request merged**
